1.What is an array?

An array is collection of items stored at contigeous memory locations. The idea is to stored multiple items of the same type together, However, user cannot constraints the type of the elements stored in a list. If you create arrays using the array module, all alements of the array must be of the same type.

2.What is difference between array and list?

Arrays can store data very compactly and are more efficient for storing large amounts of the data. Arrays are create for numerical operations; list cannot directly handle math operations. For example. you can divide each element of an array by the same number with just one line of code.

3.How to change the shape of array?

The reshape() funcyion is used to change the shape of array.

4.What does the name.strip() d0?

That returns a copy of the strings with both leading and trailing characters removed.

5.When we use triple single or triple double quotes to define a string?

To create strings that span multiple lines, triple single quotes are used to enclose the string. This string is on multiple lines within three double quotes on the either side



6.Create a character type array?

In [1]:
import numpy as np
print(np.array(['a','b','c']))

['a' 'b' 'c']


7.Create a "hello" string and access the string character "ll" in python?


In [2]:
st1='hello'
print(st1)
print(st1[2:4])

hello
ll


8.Create an array to get largest and smallest number using minimumm and maximum function?|

In [3]:
import numpy as np
a1=np.array([1,2,3,51,45,4])
print(np.max(a1))
print(np.min(a1))

51
1


9.If a name is "core python" then access the "python" from name and reverse "python" using slicing?


In [6]:
name="core python"
R=name[4:]
print(R)
R[len(R)::-1]

 python


'nohtyp '

10.Create an array of integer type and add element 12 using append method and remove one element using remove method?


In [7]:
import array as arr
a=arr.array('i',[1,2,3,4,5])
a.append(12)
print(a)
a.remove(5)
print(a)

array('i', [1, 2, 3, 4, 5, 12])
array('i', [1, 2, 3, 4, 12])


11.Create a single dimensional and 3 dimensional array using numpy?

In [9]:
import numpy as np
a=np.array([5,8,10])
print(a)
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[ 5  8 10]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


12.Create a "Programiz" string and convert the string into upper, lower case? And replace given string by "program" using replace method?

In [11]:
import numpy as np
str4="Programiz"
print(str4.upper())
print(str4.lower())
print(str4.replace('Programiz','program'))

PROGRAMIZ
programiz
program


13.Create a two array one using linspace and another using arange function and then substract?


In [13]:
import numpy as np
a1=np.linspace(3.0,4.0,5)
a2=np.arange(1,6)
print(a1-a2)

[ 2.    1.25  0.5  -0.25 -1.  ]


14.Create "happy new year" string and then separate by "," in python?


In [16]:
str1="happy new year"
print(str1)
str2="happy, new, year"
print(str2.split(","))

happy new year
['happy', ' new', ' year']
